@apiURL = {{$dotenv WEBBKOMM_API}}:8811

GET {{apiURL}}/guests

###

GET {{apiURL}}/rooms

###

GET {{apiURL}}/rooms/2


### POST skapa nytt rum
POST {{apiURL}}/rooms
Content-Type: application/json

{ 
    "number": 406, 
    "type": "double" 
}

###

GET {{apiURL}}/bookings